StartAutomating/PSDevOps

- Parts/ExpandComponents.ps1
(was outputting all values per value under certain conditions, instead of echoing value)
> Fixing duplication issue 

- Convert-BuildStep.ps1
- Expand-BuildStep.ps1
- Import-BuildStep.ps1
- New-ADOPipeline.ps1
- PSDevOps.psm1
Preparing to replacing underlying /Parts.
Adding support for parameters
> Adding Convert/Expand/Import-BuildStep

- Ado/Steps/InstallPSDevOps.ps1
- Ado/Steps/InstallPSScriptAnalyzer.ps1
- Ado/Steps/InstallPester.ps1
- Ado/Steps/RunPester.ps1
- Convert-BuildStep.ps1
- Get-ADOBuild.ps1
- Get-ADOWorkItem.ps1
- PSDevOps.tests.ps1
- azure-pipelines.yml
* Adding PesterMaxVersion to ado\steps\InstallPester.ps1 (defaulting to 4.9.9)
* Convert-BuildStep:  Allowing for [version] and [ScriptBlock[]] parameters, better support for defaultValues
* Get-ADOWorkItem: Now returning .URL
> Pester workaround

- Convert-ADOPipeline.ps1
- Get-ADOTask.ps1
- Get-ADOTeam.ps1
Adding Get-ADOTask
Adding Convert-ADOPipeline
> Tasks and converters

- Add-ADOAreaPath.ps1
- Formatting/PSDevOps.AreaPath.format.ps1
- Get-ADOAreaPath.ps1
- PSDevOps.format.ps1xml
- PSDevOps.tests.ps1
- Remove-ADOAreaPath.ps1
> Area path improvements

- Get-ADOTask.ps1
- PSDevOps.tests.ps1
Removing -apiVersion parameter.  Adding tests.
> Get-ADOTask fix

- Convert-BuildStep.ps1
- Expand-BuildStep.ps1
- GitHub/Jobs/PowerShellStaticAnalysis.psd1
- GitHub/Steps/RunScriptCop.ps1
- Hide-GitHubOutput.ps1
- New-GitHubWorkflow.ps1
- PSDevOps.tests.ps1
- Write-GitHubDebug.ps1
- Write-GitHubOutput.ps1
Renaming -EventParameter to -InputParameter, changing type to [Collections.IDictionary].
> GitHub Workflow Fixes

- Convert-ADOPipeline.ps1
- Convert-BuildStep.ps1
- Expand-BuildStep.ps1
- Import-BuildStep.ps1
- New-ADOPipeline.ps1
- New-GitHubWorkflow.ps1
- PSDevOps.psm1
Fixing static analysis errors.
Making New-ADOPipeline/New-GitHubWorkflow even more templatized.
Adding New-ADOPipeline -WindowsPowerShell/-PowerShellCore (to allow for engine selection).
> BuildStep Improvements

- Get-ADOAreaPath.ps1
- Get-ADOIterationPath.ps1
- Get-ADOProject.ps1
- Get-ADOTask.ps1
- Get-ADOTeam.ps1
- Set-ADOTeam.ps1
Improvements to -ADOProject and -ADOTeam commands:
Adding Set-ADOTeam.
Get-ADOProject:  Adding -ProcessConfiguration, -Plan, -PlanID, and -DeliveryTimeline.
Get-ADOTeam:  Adding -Setting/-FieldValue/-Iteration/-Board.
> Projects with more team work

- Add-ADODashboard.ps1
- Remove-ADODashboard.ps1
> Dashboard fixes

- Convert-ADOPipeline.ps1
- Convert-BuildStep.ps1
- New-ADOPipeline.ps1
- New-GitHubWorkflow.ps1
Convert-BuildStep: Reordering GitHub Workflow build steps.
> Build Step Enhancements

- Connect-ADO.ps1
- Formatting/PSDevOps.Field.format.ps1
- Formatting/PSDevOps.TestRun.format.ps1
- Formatting/PSDevOps.WorkProcess.Field.format.ps1
- Formatting/PSDevOps.WorkProcess.format.ps1
- Get-ADOProject.ps1
- Get-ADOWorkItemType.ps1
- Invoke-ADORestAPI.ps1
- PSDevOps.ezformat.ps1
- PSDevOps.psm1
- Types/PSDevOps.TestRun/Alias.psd1
Fixing confirmation bug when running Disconnect-ADO within another function.
Get-ADOProject:  Adding -TestRun / -TestPlan, and Progress Bars!
Get-ADOWorkItemType:  Adding -Field
Formatter definition updates.
> Additional ado

- Ado/Stages/TestPowerShellCrossPlatform.psd1
- Ado/Steps/PublishCodeCoverage.psd1
- Ado/Steps/PublishTestResults.psd1
- Ado/Steps/RunPSScriptAnalyzer.ps1
- Ado/Steps/RunPester.ps1
- Ado/Steps/RunScriptCop.ps1
- Convert-BuildStep.ps1
- GitHub/Jobs/TestPowerShellOnLinux.psd1
- GitHub/Steps/Checkout.psd1
- GitHub/Steps/PublishTestResults.psd1
- GitHub/Steps/RunPester.ps1
- PSDevOps.Pipeline.PSDevOps.ps1
- PSDevOps.tests.ps1
- azure-pipelines.yml
> Improvements to Azure DevOps pipelines and workflows

- Add-ADOPicklist.ps1
- Convert-BuildStep.ps1
- Get-ADOPicklist.ps1
- Get-ADOProject.ps1
- Get-ADORepository.ps1
- PSDevOps.psd1
- PSDevOps.tests.ps1
- Parts/GetInvokeParameters.ps1
- Start-ADOBuild.ps1
- Update-ADOPicklist.ps1
- Wait-ADOBuild.ps1
Get-ADORepository:  Adding -IncludeHidden, -IncludeLink, -IncludeRemoteUrl (Issue #66)
Start-ADOBuild:  Fixing parameter passdown bug (Issue #67 )
Start-ADOBuild:  Allowing parameters to be passed as a PSObject.
Test updates
> Little ado fixes

- Formatting/PSDevOps.TestPlan.format.ps1
- Formatting/PSDevOps.TestSuite.format.ps1
- Get-ADOTest.ps1
- PSDevOps.format.ps1xml
- PSDevOps.psd1
- PSDevOps.types.ps1xml
- Types/PSDevOps.TestPlan/Alias.psd1
- Types/PSDevOps.TestSuite/get_LastUpdated.ps1
Fixing Get-ADOTest, adding formatters / types for various subparameters.
> Fixing Get-ADOTest

- Get-ADOTest.ps1
- Invoke-ADORestAPI.ps1
Allowing Get-ADOTest to paginate thru results, and autopaginating with -Total.  Fixing #86
> Get-ADOTest Fix

- Formatting/PSDevOps.WorkItem.Comment.format.ps1
- Formatting/PSDevOps.WorkItem.CommentReaction.format.ps1
- Get-ADOWorkItem.ps1
- Invoke-ADORestAPI.ps1
- New-ADOWorkItem.ps1
- New-ADOWorkItemType.ps1
- New-ADOWorkProcess.ps1
- PSDevOps.format.ps1xml
- PSDevOps.psd1
- PSDevOps.tests.ps1
- PSDevOps.types.ps1xml
- Parts/GetInvokeParameters.ps1
- Set-ADOWorkItem.ps1
- Set-ADOWorkProcess.ps1
- Types/PSDevOps.WorkItem.Comment/Alias.psd1
- Types/PSDevOps.WorkItem.Comment/get_Comment.ps1
- Types/PSDevOps.WorkItem.Comment/get_CreatedAt.ps1
- Types/PSDevOps.WorkItem.Comment/get_ModifiedAt.ps1
- Types/PSDevOps.WorkItem.Comment/get_Reaction.ps1
- Types/PSDevOps.WorkItem/AddComment.ps1
Get-ADOWorkItem:
Fixing -Related #79 
Fixing -Comment errors when there are no commments #80 
New/Set-ADOWorkItem:
Adding -Relationship and -Comment #81 
Improving Formatting of Work Items #82
> WorkItem Improvements

- Get-ADOBuild.ps1
- PSDevOps.types.ps1xml
- Types/PSDevOps.Build.Artifact/Download.ps1
- Types/PSDevOps.Build.Artifact/get_ArtifactData.ps1
- Types/PSDevOps.Build.Artifact/get_ArtifactType.ps1
Fixing #113 
Also attempting to avoid errors in accumulation
> Get-ADOBuild improvements

- .github/workflows/IssueOpenedOrEdited.yml
- .github/workflows/TestAndPublish.yml
- .github/workflows/TraceIssueOpenedOrEdited.yml
- GitHub/Jobs/TraceGitHubEvent.psd1
- GitHub/On/IssueClosed.psd1
- GitHub/On/IssueEdited.psd1
- GitHub/On/IssueOpened.psd1
- GitHub/On/IssueOpenedOrEdited.psd1
- GitHub/Steps/ReleaseModule.ps1
- GitHub/Steps/TraceGitHubEvent.ps1
Updating GitHub Step ReleaseModule (and workflow).  Fixing #130
Enabling GitHub workflow triggers on issue opened, closed, and modified.  Fixing #132
> GitHub Workflow Improvements

- CHANGELOG.md
- Formatting/PSDevOps.AreaPath.format.ps1
- Formatting/PSDevOps.IterationPath.format.ps1
- Get-ADOAreaPath.ps1
- Get-ADOIterationPath.ps1
- Get-ADOPermission.ps1
- PSDevOps.format.ps1xml
- PSDevOps.psd1
- PSDevOps.types.ps1xml
- Set-ADOPermission.ps1
- Types/PSDevOps.AreaPath/Alias.psd1
- Types/PSDevOps.Build.Definition/Alias.psd1
- Types/PSDevOps.IterationPath/Alias.psd1
Enabling easier permission sets (addresses #128)
Enabling permissions for area paths  (addresses #107)
Supporting changes to AreaPaths/IterationPaths/BuildDefintions
> Updating Get/Set-ADOPermission:  

- CHANGELOG.md
- Get-ADOPermission.ps1
- Get-ADOServiceEndpoint.ps1
- PSDevOps.psd1
- PSDevOps.types.ps1xml
- Set-ADOPermission.ps1
- Types/PSDevOps.WorkProcess/Alias.psd1
Fixing: 
* #136 
* #137 
* #138
> More permissions
